name: "Deploy to GitHub Pages"

on:
    push:
        branches:
            - master
            - main

permissions:
  contents: read
  actions: write
  checks: write

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build
            
            - name: Test
              run: npm test --reporters="default"
            
            - name: Test Report
              uses: dorny/test-reporter@v1
              if: success() || failure()    # run this step even if previous step failed
              with:
                name: JEST Tests            # Name of the check run which will be created
                path: reports/report.xml    # Path to test results
                reporter: jest-junit        # Format of test results

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v4
              if: success()
              with:
                  github_token: ${{ secrets.PERSONAL_TOKEN }}
                  publish_dir: ./dist
                  publish_branch: gh-pages